//
//  File.swift
//  
//
//  Created by Alexey on 21.03.2023.
//

import Foundation

public enum Country: Int {
    case russia = 0
    case ukraine
    case kazakhstan
    case china
    case philippines
    case myanmar
    case indonesia
    case malaysia
    case kenya
    case tanzania
    case vietnam
    case kyrgyzstan
    case usa
    case israel
    case hongkong
    case poland
    case england
    case madagascar
    case dcongo
    case nigeria
    case macao
    case egypt
    case india
    case ireland
    case cambodia
    case laos
    case haiti
    case ivory
    case gambia
    case serbia
    case yemen
    case southafrica
    case romania
    case colombia
    case estonia
    case canada
    case morocco
    case ghana
    case argentina
    case uzbekistan
    case cameroon
    case chad
    case germany
    case lithuania
    case croatia
    case sweden
    case iraq
    case netherlands
    case latvia
    case austria
    case belarus
    case thailand
    case saudiarabia
    case mexico
    case taiwan
    case spain
    case algeria
    case slovenia
    case bangladesh
    case senegal
    case turkey
    case czech
    case srilanka
    case peru
    case pakistan
    case newzealand
    case guinea
    case mali
    case venezuela
    case ethiopia
    case mongolia
    case brazil
    case afghanistan
    case uganda
    case angola
    case cyprus
    case france
    case papua
    case mozambique
    case nepal
    case belgium
    case bulgaria
    case hungary
    case moldova
    case italy
    case paraguay
    case honduras
    case tunisia
    case nicaragua
    case timorleste
    case bolivia
    case costarica
    case guatemala
    case uae
    case zimbabwe
    case puertorico
    case togo
    case kuwait
    case salvador
    case libyan
    case jamaica
    case trinidad
    case ecuador
    case swaziland
    case oman
    case bosnia
    case dominican
    case qatar
    case panama
    case mauritania
    case sierraleone
    case jordan
    case portugal
    case barbados
    case burundi
    case benin
    case brunei
    case bahamas
    case botswana
    case belize
    case caf
    case dominica
    case grenada
    case georgia
    case greece
    case guineabissau
    case guyana
    case iceland
    case comoros
    case saintkitts
    case liberia
    case lesotho
    case malawi
    case namibia
    case niger
    case rwanda
    case slovakia
    case suriname
    case tajikistan
    case monaco
    case bahrain
    case reunion
    case zambia
    case armenia
    case somalia
    case congo
    case chile
    case burkinafaso
    case lebanon
    case gabon
    case albania
    case uruguay
    case mauritius
    case bhutan
    case maldives
    case guadeloupe
    case turkmenistan
    case frenchguiana
    case finland
    case saintlucia
    case luxembourg
    case saintvincentgrenadines
    case equatorialguinea
    case djibouti
    case antiguabarbuda
    case caymanislands
    case montenegro
    case denmark
    case switzerland
    case norway
    case australia
    case eritrea
    case southsudan
    case saotomeandprincipe
    case aruba
    case montserrat
    case anguilla
    case northmacedonia
    case seychelles
    case newcaledonia
    case capeverde
    case usaphysical
    case fiji
    case singapore
}
